##### 1) Load the Iris dataset as a list of lists (each of the 150 lists should have 5 elements). Compute and print the mean and the standard deviation for each of the 4 measurement columns (i.e. sepal length and width, petal length and width). Compute and print the mean and the standard deviation for each of the 4 measurement columns, separately for each of the three Iris species (Versicolor, Virginica and Setose). Which measurement would you consider “best”, if you were to guess the Iris species based only on those four values? 

In [112]:
import pandas as pd


In [113]:
#from google.colab import drive
#drive.mount('/content/drive')

In [5]:
df = pd.read_csv("iries_train_data.csv")
df.head()

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
0          69           5.6          2.5           3.9          1.1   
1         117           7.7          3.8           6.7          2.2   
2         103           6.3          2.9           5.6          1.8   
3          61           5.9          3.0           4.2          1.5   
4         101           5.8          2.7           5.1          1.9   

           species  
0  Iris-versicolor  
1   Iris-virginica  
2   Iris-virginica  
3  Iris-versicolor  
4   Iris-virginica

In [6]:
df.describe()

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width
count  120.000000    120.000000   120.000000    120.000000   120.000000
mean    75.158333      5.863333     3.032500      3.801667     1.208333
std     43.469297      0.834541     0.422709      1.734571     0.746936
min      0.000000      4.400000     2.000000      1.000000     0.100000
25%     41.500000      5.100000     2.800000      1.600000     0.300000
50%     74.500000      5.800000     3.000000      4.350000     1.300000
75%    113.250000      6.400000     3.300000      5.100000     1.800000
max    149.000000      7.900000     4.400000      6.900000     2.500000

In [7]:
df.head()

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
0          69           5.6          2.5           3.9          1.1   
1         117           7.7          3.8           6.7          2.2   
2         103           6.3          2.9           5.6          1.8   
3          61           5.9          3.0           4.2          1.5   
4         101           5.8          2.7           5.1          1.9   

           species  
0  Iris-versicolor  
1   Iris-virginica  
2   Iris-virginica  
3  Iris-versicolor  
4   Iris-virginica

In [ ]:
#df.shape,df.columns

In [8]:
df["species"].value_counts()

Iris-versicolor    42
Iris-virginica     40
Iris-setosa        38
Name: species, dtype: int64

In [13]:
print("sepal_length mean and Deviation is ", df["sepal_length"].mean(),df["sepal_length"].std())


sepal_length mean and Deviation is  5.863333333333333 0.8345414212329437


In [14]:
print("sepal_width mean and Deviation is ", df["sepal_width"].mean(),df["sepal_width"].std())
    

sepal_width mean and Deviation is  3.0324999999999998 0.4227088514678201


In [16]:
print("petal_length mean and Deviation is ", df["petal_length"].mean(),df["petal_length"].std())

petal_length mean and Deviation is  3.8016666666666667 1.7345710405393806


In [17]:
print("petal_length mean and Deviation is ", df["petal_width"].mean(),df["petal_width"].std())

petal_length mean and Deviation is  1.2083333333333333 0.7469358508373434


In [18]:
 df[df['species']=="Iris-versicolor"].mean()

C:\Users\Language Lab\AppData\Local\Temp\ipykernel_5012\1808947818.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['species']=="Iris-versicolor"].mean()


Unnamed: 0      73.785714
sepal_length     5.964286
sepal_width      2.771429
petal_length     4.235714
petal_width      1.319048
dtype: float64

In [19]:
 df[df['species']=="Iris-setosa"].mean()

C:\Users\Language Lab\AppData\Local\Temp\ipykernel_5012\1346809083.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['species']=="Iris-setosa"].mean()


Unnamed: 0      24.000000
sepal_length     4.986842
sepal_width      3.400000
petal_length     1.481579
petal_width      0.244737
dtype: float64

In [20]:
 df[df['species']=="Iris-virginica"].mean()

C:\Users\Language Lab\AppData\Local\Temp\ipykernel_5012\3146510401.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df['species']=="Iris-virginica"].mean()


Unnamed: 0      125.2000
sepal_length      6.5900
sepal_width       2.9575
petal_length      5.5500
petal_width       2.0075
dtype: float64

# Exp-5 to split data into train and test

In [21]:
#train_data=df.sample(frac=.8)

In [22]:
#train_data["species"].value_counts()

In [23]:
#test_data=df.loc[~df.index.isin(train_data.index)]

In [24]:
#test_data["species"].value_counts()

In [45]:
df1=df.drop("petal_width",axis=1)
df1.head()

Unnamed: 0  sepal_length  sepal_width  petal_length          species
0          69           5.6          2.5           3.9  Iris-versicolor
1         117           7.7          3.8           6.7   Iris-virginica
2         103           6.3          2.9           5.6   Iris-virginica
3          61           5.9          3.0           4.2  Iris-versicolor
4         101           5.8          2.7           5.1   Iris-virginica

In [46]:
df1.head()

Unnamed: 0  sepal_length  sepal_width  petal_length          species
0          69           5.6          2.5           3.9  Iris-versicolor
1         117           7.7          3.8           6.7   Iris-virginica
2         103           6.3          2.9           5.6   Iris-virginica
3          61           5.9          3.0           4.2  Iris-versicolor
4         101           5.8          2.7           5.1   Iris-virginica

In [47]:
from sklearn.model_selection import train_test_split
train,test= train_test_split(df1,test_size=0.2)
df1.head()


Unnamed: 0  sepal_length  sepal_width  petal_length          species
0          69           5.6          2.5           3.9  Iris-versicolor
1         117           7.7          3.8           6.7   Iris-virginica
2         103           6.3          2.9           5.6   Iris-virginica
3          61           5.9          3.0           4.2  Iris-versicolor
4         101           5.8          2.7           5.1   Iris-virginica

In [48]:
len(train),len(test)

(96, 24)

In [49]:
train.head(10)

Unnamed: 0  sepal_length  sepal_width  petal_length          species
50            2           4.7          3.2           1.3      Iris-setosa
0            69           5.6          2.5           3.9  Iris-versicolor
72            6           4.6          3.4           1.4      Iris-setosa
45           87           6.3          2.3           4.4  Iris-versicolor
108          88           5.6          3.0           4.1  Iris-versicolor
105         132           6.4          2.8           5.6   Iris-virginica
16           19           5.1          3.8           1.5      Iris-setosa
37           24           4.8          3.4           1.9      Iris-setosa
47           31           5.4          3.4           1.5      Iris-setosa
31           81           5.5          2.4           3.7  Iris-versicolor

In [50]:
train["species"].value_counts()

Iris-versicolor    34
Iris-virginica     33
Iris-setosa        29
Name: species, dtype: int64

In [51]:
test["species"].value_counts()

Iris-setosa        9
Iris-versicolor    8
Iris-virginica     7
Name: species, dtype: int64

In [52]:
train.to_csv('Iries_train_data.csv',index=False)
test.to_csv('Iries_test_data.csv',index=False)
df.head()

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
0          69           5.6          2.5           3.9          1.1   
1         117           7.7          3.8           6.7          2.2   
2         103           6.3          2.9           5.6          1.8   
3          61           5.9          3.0           4.2          1.5   
4         101           5.8          2.7           5.1          1.9   

           species  
0  Iris-versicolor  
1   Iris-virginica  
2   Iris-virginica  
3  Iris-versicolor  
4   Iris-virginica

In [53]:
train_df = pd.read_csv("Iries_train_data.csv")
test_df= pd.read_csv("Iries_test_data.csv")
df1.head()

Unnamed: 0  sepal_length  sepal_width  petal_length          species
0          69           5.6          2.5           3.9  Iris-versicolor
1         117           7.7          3.8           6.7   Iris-virginica
2         103           6.3          2.9           5.6   Iris-virginica
3          61           5.9          3.0           4.2  Iris-versicolor
4         101           5.8          2.7           5.1   Iris-virginica

In [54]:
train_df.head()

Unnamed: 0  sepal_length  sepal_width  petal_length          species
0           2           4.7          3.2           1.3      Iris-setosa
1          69           5.6          2.5           3.9  Iris-versicolor
2           6           4.6          3.4           1.4      Iris-setosa
3          87           6.3          2.3           4.4  Iris-versicolor
4          88           5.6          3.0           4.1  Iris-versicolor

In [77]:
# how many missing values are there Train data?
train_df.isnull().sum()


Unnamed: 0      0
sepal_length    0
sepal_width     0
petal_length    0
species         0
dtype: int64

In [62]:
#what is the propotion of "sertosa" in test dataset?
sertosa_count=test_df[test_df["species"]=="Iris-setosa"].value_counts().sum()
df1.head()
#print("propotion of sertosa in test dataset", )

Unnamed: 0  sepal_length  sepal_width  petal_length          species
0          69           5.6          2.5           3.9  Iris-versicolor
1         117           7.7          3.8           6.7   Iris-virginica
2         103           6.3          2.9           5.6   Iris-virginica
3          61           5.9          3.0           4.2  Iris-versicolor
4         101           5.8          2.7           5.1   Iris-virginica

## What is the accuracy score of the K-Nearest Neighbor model (model_1) with 2/3 neighbors using Train_Data and Test_Data? 

In [64]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier(n_neighbors=2)
df.head()

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width  \
0          69           5.6          2.5           3.9          1.1   
1         117           7.7          3.8           6.7          2.2   
2         103           6.3          2.9           5.6          1.8   
3          61           5.9          3.0           4.2          1.5   
4         101           5.8          2.7           5.1          1.9   

           species  
0  Iris-versicolor  
1   Iris-virginica  
2   Iris-virginica  
3  Iris-versicolor  
4   Iris-virginica

In [65]:
x_train=train_df.drop('species',axis=1)
y_train=train_df["species"]
x_test=test_df.drop('species',axis=1)
y_test=test_df["species"]

In [66]:
x_train.head()

Unnamed: 0  sepal_length  sepal_width  petal_length
0           2           4.7          3.2           1.3
1          69           5.6          2.5           3.9
2           6           4.6          3.4           1.4
3          87           6.3          2.3           4.4
4          88           5.6          3.0           4.1

In [67]:
y_train.head()

0        Iris-setosa
1    Iris-versicolor
2        Iris-setosa
3    Iris-versicolor
4    Iris-versicolor
Name: species, dtype: object

In [68]:
x_test[:5]

Unnamed: 0  sepal_length  sepal_width  petal_length
0          56           6.3          3.3           4.7
1          42           4.4          3.2           1.3
2          58           6.6          2.9           4.6
3          27           5.2          3.5           1.5
4         130           7.4          2.8           6.1

In [69]:
knn.fit(x_train,y_train)# training phase 

KNeighborsClassifier(n_neighbors=2)

In [70]:
score=knn.score(x_test,y_test)
score

1.0

In [71]:
pred=knn.predict(x_test)
pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

In [72]:
y_test

0     Iris-versicolor
1         Iris-setosa
2     Iris-versicolor
3         Iris-setosa
4      Iris-virginica
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9      Iris-virginica
10    Iris-versicolor
11        Iris-setosa
12     Iris-virginica
13    Iris-versicolor
14        Iris-setosa
15    Iris-versicolor
16    Iris-versicolor
17     Iris-virginica
18     Iris-virginica
19    Iris-versicolor
20        Iris-setosa
21     Iris-virginica
22    Iris-versicolor
23     Iris-virginica
Name: species, dtype: object

In [73]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [74]:
print(confusion_matrix(y_test,pred))

[[9 0 0]
 [0 8 0]
 [0 0 7]]


In [75]:
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00         7

       accuracy                           1.00        24
      macro avg       1.00      1.00      1.00        24
   weighted avg       1.00      1.00      1.00        24



## Build a logistic regression model (model_2) keeping the modelling steps constant. Find the accuracy of the model_2 

In [78]:
from sklearn.linear_model import LogisticRegression

In [79]:
model2=LogisticRegression()

In [80]:
model2.fit(x_train,y_train)

C:\Users\Language Lab\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [81]:
pred=model2.predict(x_test)

In [82]:
pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

In [83]:
accuracy_score(y_test,pred)

1.0

In [84]:
confusion_matrix(y_test,pred)

array([[9, 0, 0],
       [0, 8, 0],
       [0, 0, 7]], dtype=int64)

In [85]:
print(classification_report(y_test,pred))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00         7

       accuracy                           1.00        24
      macro avg       1.00      1.00      1.00        24
   weighted avg       1.00      1.00      1.00        24



## Exp-7 :Demonstrate Decision tree classification model and Evaluate the performance of classifier on Iris

In [86]:
from sklearn.tree import DecisionTreeClassifier

In [87]:
clf=DecisionTreeClassifier(max_depth=3,random_state=42)

In [ ]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [89]:
confusion_matrix(y_test,pred)

array([[9, 0, 0],
       [0, 8, 0],
       [0, 0, 7]], dtype=int64)

In [ ]:
accuracy_score(y_test,pred)

0.9666666666666667

In [ ]:
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.88      0.93         8
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30



# Demonstrate any of the Clustering model and Evaluate the performance on Iris dataset. 

In [111]:
from sklearn.cluster import KMeans

In [94]:
km=KMeans(n_clusters=3)

In [96]:
km.fit(x_train,y_train)

C:\Users\Language Lab\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=3)

In [97]:
km.labels_[:10]

array([0, 2, 0, 2, 2, 1, 0, 0, 0, 2])

In [98]:
pred=km.predict(x_test)

In [99]:
pred[:10]

array([2, 0, 2, 0, 1, 0, 0, 2, 0, 1])

In [100]:
km.cluster_centers_

array([[ 18.20833333,   4.97916667,   3.35      ,   1.47916667],
       [120.62162162,   6.44864865,   2.92972973,   5.38378378],
       [ 68.71428571,   5.86571429,   2.88571429,   3.9       ]])

In [101]:
y_test

0     Iris-versicolor
1         Iris-setosa
2     Iris-versicolor
3         Iris-setosa
4      Iris-virginica
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9      Iris-virginica
10    Iris-versicolor
11        Iris-setosa
12     Iris-virginica
13    Iris-versicolor
14        Iris-setosa
15    Iris-versicolor
16    Iris-versicolor
17     Iris-virginica
18     Iris-virginica
19    Iris-versicolor
20        Iris-setosa
21     Iris-virginica
22    Iris-versicolor
23     Iris-virginica
Name: species, dtype: object

In [102]:
from sklearn import datasets

In [103]:
iris=datasets.load_iris()

In [104]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [105]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [106]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [109]:
km=KMeans(n_clusters=3)

In [110]:
km.fit(iris.data,iris.target)

C:\Users\Language Lab\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=3)

In [ ]:
km.cluster_centers_

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [ ]:
km.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
import numpy as np


In [ ]:
pred=np.choose(km.labels_,[1,0,2]).astype(np.int64)

In [ ]:
confusion_matrix(pred,iris.target)

array([[50,  0,  0],
       [ 0, 48, 14],
       [ 0,  2, 36]], dtype=int64)

In [ ]:
accuracy_score(iris.target,pred)

0.8933333333333333